# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShareSpace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShareSpace
  # Pods for Pursuit-Core-iOS-Firebase-Project
  pod 'Firebase/Auth'
  
  #Database Pods
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  
  # Storage is used to store media files
  pod 'Firebase/Storage'
  
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'JTAppleCalendar'

  target 'ShareSpaceTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestoreSwift'
    pod 'Firebase/Storage'

  end

end
